Question 1

Write a Python program to convert an array to an ordinary list with the same items.

we can use the np.tolist() function

Question 2 

Write a NumPy program to compute the sum of the diagonal elements of a given array.

Hint: Two methods to solve this problem: 1. manually(without direct function). 2. using the trace function

Question 3

Given an array of your choice, get all the values higher than X :

if a = [[1,2],[3,5]] and x = 2 :  then 3 and 5 are higher than 2. 

Question 4

Given two arrays, A & B have the same shape. 

The task is to apply addition by hand: C is the new array. 

Question 5

Write a NumPy program to subtract the mean of each row of a given matrix.

Hint: use the mean function

In [58]:
print ('QUESTION 1')
array = np.array ([[2,4,6] , [8,10,12]])
print (array)

conversion = array.tolist()
print ('list: ', conversion)

QUESTION 1
[[ 2  4  6]
 [ 8 10 12]]
list:  [[2, 4, 6], [8, 10, 12]]


In [71]:
print ('QUESTION 2')
import numpy as np

array = np.array([[55, 25, 15], [30, 44, 2],[11, 45, 77]])

print("Original Matrix:")
print(array)

trace = np.trace(n_array)
print("\nTrace of given 3X3 matrix:")
print(trace)

QUESTION 2
Original Matrix:
[[55 25 15]
 [30 44  2]
 [11 45 77]]

Trace of given 3X3 matrix:
176


In [67]:
print ('QUESTION 3')
import numpy as np
array = np.array([[1,2,3], [4,5,6],[7,8,9]] )
print (array)

x=7
print ('\n')
print (array[array>x])


QUESTION 3
[[1 2 3]
 [4 5 6]
 [7 8 9]]


[8 9]


In [68]:
print ('QUESTION 4')
import numpy as np
A = np.array([[1,7],[3,4]],dtype=int ) 
B = np.array([[5,6],[7,10]],dtype=int )  

C = A + B
print (C)

QUESTION 4
[[ 6 13]
 [10 14]]


In [70]:
print ('QUESTION 5')
import numpy as np
array = np.array([[5,17,8], [18,42,76],[7,10,18]] )
print ('Original matrix:')
print (array)

x= array - array.mean(axis = 1 , keepdims = True , dtype=int)
print ("\n")
print (x)

QUESTION 5
Original matrix:
[[ 5 17  8]
 [18 42 76]
 [ 7 10 18]]


[[ -5   7  -2]
 [-27  -3  31]
 [ -4  -1   7]]
